apiVersion: v1
kind: Service
metadata:
  name: amazonprimeclone-service
spec:
  selector:
    app: amazonprimeclone
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
